DAPI-347: Initial commit notification sample app
mitel-networks/developer-api-program pull request #3
Opened 2022-04-26 12:42 UTC by mitel-prashant

Resolves [DAPI-347](https://mitel.atlassian.net/browse/DAPI-347)

This PR fix DAPI-347 - This sample code makes use of the Create Subscription endpoint to create a subscription for ringing events on a range of endpoints defined by the user. This sample code is expected to output any received webhooks to the console.

2022-04-28 01:06 UTC, FerrissK requested changes

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +        const response = await fetch('https://authentication.dev.api.mitel.io/2017-09-01/authorize', {
This auth call should point to the public cloud

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +        // Call the code api to obtain the valid code
This should read: // Call the auth api to obtain a valid code

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +    const token = await getToken(userCode.code, inputData.appData.client_id);
Should validate userCode before using in the getToken

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +        const response = await fetch('https://authentication.dev.api.mitel.io/2017-09-01/token', {
Should call public cloud

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +        const response = await fetch('https://notifications.dev.api.mitel.io/2017-09-01/subscriptions', {
Should call public cloud

2022-04-28 01:06 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +        const response = await fetch(`https://media.dev.api.mitel.io/2017-09-01/endpoints/${inputData.makeCallData.from}/calls`, {
Should call public cloud

2022-04-28 13:27 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +[Node.js](https://nodejs.org/en/) - Install node.js
We should probably add having a cloudlink account and obtaining a cliend Id as pre- requisites.

@buddrenaud, maybe we can link or at least tell where they can read your get starting doc?

2022-04-28 13:28 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        username: "USER_NAME",       // provide your username for user 1
We should specify that this is a Cloudlink username/ password

2022-04-28 13:30 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        applicationId: "APPLICATION_ID", // 128-bit GUID that identifies the application for trust/signing purposes
I got confused over what an APPLICATION_ID was, we should be more specific that this is an ID that you specify.

2022-04-28 13:33 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        deviceId: "DEVICE_ID", //URL for webhooks to be delivered to
Add https://webhook.site/ as an example?

2022-04-28 19:19 UTC, FerrissK requested changes

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        applicationId: "APPLICATION_ID", // This is a unique ID specific to your app that’s required if you’re using a webhooks. You can generate this yourself, just make sure it’s unique, so somethi
Change 'using a webhooks' -> 'using a webhook'

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +* Have an cloudlink account and obtain a client id
Should we add that you can obtain more information on this through the [Developer Portal](https://developer.mitel.io/)?

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
>          account_id: "ACCOUNT_ID",    // provide account_id for user
Again, I would add Cloudlink account ID.

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        username: "USER_NAME",       // this is your cloudlink user
I would capitalize Cloudlink

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/README.md
> +        password: "PASSWORD",        // provide password for your cloudlink user
I would capitalize Cloudlink

2022-04-28 19:19 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/inputData.js
> +        username: "USER_NAME",       // this is your cloudlink user
Update this file with the comments from the Readme file.

2022-04-28 19:26 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +    const token = await getToken(userCode.code, inputData.appData.client_id);
Should check userCode for null/ undefined and log out message.

2022-04-28 19:48 UTC, mitel-prashant commented on sample-app/notification-sample-code/nodejs/index.js
> +    const token = await getToken(userCode.code, inputData.appData.client_id);
Below code added in every function will log the exact error coming from API and exit the flow

// If response code is greater than 201, stop the execution and terminate the program
if (response.status > 201) {
	console.log(await response.json());
	process.exit();
}

2022-04-29 14:49 UTC, FerrissK commented on sample-app/notification-sample-code/nodejs/index.js
> +    const token = await getToken(userCode.code, inputData.appData.client_id);
Pefect, I will resolve this conversation.

2022-04-29 14:52 UTC, FerrissK approved these changes

2022-05-02 13:08 UTC, merged